### ISSUE TITLE
Argument that avoids the explorer.exe

### ISSUE THREAD

**Issue by Leitonez** [kybu/headless-selenium-for-win#11]
Hello!
Congratulations on developing desktop_utils. It really is a program that helps me a lot.
There is a small problem. Every time a program is run on a virtual desktop, a new process "explorer.exe" is started.
It would be interesting if we could pass a parameter to not start this process...
Thank you very much in advance.

**Comment by kybu** [comment]
Hi,

Thanks for using `desktop_utils`.

`explorer.exe` is started for each virtual desktop, so that you get the toolbar etc. Also, some desktop applications directly communicate with `explorer.exe` and would not work correctly otherwise. So it is always started to be on the safe side. However, I can add an option to not start it for people who would like to tinker with it.

**Comment by Leitonez** [comment]
Yes, please! That would be great. Thank you!
